import { v4 } from 'uuid';

export const tableData = [
  {
    id: v4(),
    idTracking: 2143135,
    product: 'Apple iPad mini 2021',
    img: 'https://mzimg.com/big/j1/gugywbo02j1.jpg',
    customer: 'Chaim Lewis',
    date: '28 July',
    price: 880,
    method: 'Cash on Delivery',
    status: 'Approved',
  },
  {
    id: v4(),
    idTracking: 2637235,
    product: 'Playstation 5',
    img: 'https://mzimg.com/big/n1/gfpmqomkzn1.jpg',
    customer: 'Michael Doe',
    date: '28 July',
    price: 900,
    method: 'Online Payment',
    status: 'Pending',
  },
  {
    id: v4(),
    idTracking: 2642853,
    product: 'Monitor 2E G2721B',
    img: 'https://s.ek.ua/jpg_zoom1/2203216.jpg',
    customer: 'Allen Raymond',
    date: '28 July',
    price: 450,
    method: 'Cash on Delivery',
    status: 'Pending',
  },
  {
    id: v4(),
    idTracking: 2357791,
    product: 'HyperX Cloud Alpha',
    img: 'https://s.ek.ua/jpg_zoom1/1193298.jpg',
    customer: 'Cyrus Jackson',
    date: '28 July',
    price: 125,
    method: 'Online Payment',
    status: 'Approved',
  },
  {
    id: v4(),
    idTracking: 2347358,
    product: 'Apple iPhone 13 Pro',
    img: 'https://s.ek.ua/jpg_zoom1/2090047.jpg',
    customer: 'Harold Carol',
    date: '28 July',
    price: 1350,
    method: 'Online Payment',
    status: 'Delivered',
  },
];
